name: 'Setup Minio Client'
description: 'Setup the minio client (mc) on GitHub Actions'

branding:
  icon: 'play'
  color: 'blue'

inputs:
  version:
    description: 'Minio client version, use latest to fetch latest version'
    required: false
    default: 'latest'

runs:
  using: 'node20'
  main: 'dist/index.js'
